services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    restart: always
  user-service:
    build: .
    ports:
      - 8081:8081
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/user_db
      DB_USER: postgres
      DB_PASSWORD: secret
    container_name: user_service_app
    depends_on:
      - postgres
    restart: always

